name: Validate Bambdas

on:
  pull_request:

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: "21"

      - name: Verify BambdaChecker checksum
        run: |
          expected="085787c80b9f70f431c6f5a329cf59385b67e69d74116b11e5c4ccbc021ec3d6"
          actual=$(sha256sum BambdaChecker-1.5.jar | awk '{print $1}')

          if [ "$actual" != "$expected" ]; then
            echo "Checksum mismatch!"
            echo "Expected: $expected"
            echo "Actual:   $actual"
            exit 1
          fi

      - name: Prepare validation directory
        run: |
          mkdir validation

          find . \
            -path "./validation" -prune -o \
            -name "*.bambda" \
            -exec cp {} validation/ \;

          echo "Bambdas encontrados:"
          ls -l validation

      - name: Validate Bambdas
        run: |
          cd validation
          java -jar ../BambdaChecker-1.5.jar validateonly